### ISSUE TITLE
Root permissions error.

### ISSUE THREAD

**Issue by adriass** [eReuse/device-inventory#1]
When is executed without root privileges, it returns the following error:

```
user@computer:~/GitHub/device-inventory/device_inventory$ python donator.py 
Only root can run this script

** COLLECTED WARNINGS **
Failed to open memory buffer (/dev/mem): Permission denied
No SMBIOS nor DMI entry point found, sorry.
** END OF WARNINGS **
```

**Comment by ivilata** [comment]
I think the error in the first line is quite explanatory. @dfranquesa, shall we close this issue?

**Comment by dfranquesa** [comment]
Yes. Thank you. David

El dia 7 des. 2016 10:12 a. m., "Ivan Vilata-i-Balaguer" <
notifications@github.com> va escriure:

**Comment by adriass** [comment]
Alrigth, I'm closing this.
