### ISSUE TITLE
Could not read from one OptiPlex 330

### ISSUE THREAD

**Issue by bustawin** [eReuse/device-inventory#4]
The objective is to know why NO_COMPUTER_ID_GENERATED.json (label 62) from TxT did not generate a S/N.

- There are other Optiplex 330 that generated a S/N.

As now, computers that do not generate HID cannot be registered, so this is important to know.

@adriajk or I can execute again DeviceInventory to that computer, if need it.

**Comment by slamora** [comment]
There are two OptiPlex 330:
- FG3MB3J (label 47)
- NO_COMPUTER_ID_GENERATED (label 62)

Checking the dmidecode output, serial number field is empty for the second one, so this is not a issue on device-inventory but on dmidecode or just shows that manufacturer doesn't fill this field.

```
# label 47 (partial DMI)
Handle 0x0100, DMI type 1, 27 bytes
System Information
    Manufacturer: Dell Inc.
    Product Name: OptiPlex 330    
    Version: Not Specified
    Serial Number: FG3MB3J
    UUID: [PRIVATE_VALUE]
    Wake-up Type: APM Timer
    SKU Number: Not Specified
    Family: Not Specified

# label 62 (partial DMI)
Handle 0x0100, DMI type 1, 27 bytes
System Information
    Manufacturer: Dell Inc.
    Product Name: OptiPlex 330    
    Version: Not Specified
    Serial Number:      
    UUID: Not Present
    Wake-up Type: APM Timer
    SKU Number: Not Specified
    Family: Not Specified

```

**Comment by bustawin** [comment]
@slamora DeviceHub is already thought to be able to handle computers without HID, however the matching of computers without HID is not developed yet, as https://github.com/eReuse/DeviceHub/commit/4c24d69feb33b66fb4d412ba2d64b7f83b26cbf0 I deactivate registering a computer more than once, but with or without HID, until this is developed.
