### ISSUE TITLE
Access to the smb folder

### ISSUE THREAD

**Issue by bustawin** [eReuse/device-inventory#47]
Accessing to `smb://192.168.2.2/` from Mac results in a failed connection. I remember that we should access to a specific folder under `192.268.2.2` but there is no mention about it in the documentation.

In my poor knowledge, I tried to know which folders the server is sharing with `smbstatus` but I received access denied errors, which leads to another problem: there are no the credentials for `root` in the documentation.

![ereusepxeserver-7_1a4__running__and_issues_ _ereuse_device-inventory](https://cloud.githubusercontent.com/assets/4247265/20037086/da59f454-a419-11e6-934b-2f03ef46c5d2.png)

**Comment by ivilata** [comment]
The root password is available in the description field of the VM in VirtualBox, but I added it to the end of ``PXE_Register.md``. To access the SMB share your computer must connect to the same network as the VM and get DHCP configuration from it. I also documented this there in commit b619e7c.
