### ISSUE TITLE
Wrong unit values

### ISSUE THREAD

**Issue by bustawin** [eReuse/device-inventory#50]
DDI can sometimes generate wrong unit sizes (ex. setting a value in MB when GB is required), like in [this JSON](https://github.com/eReuse/DeviceHub/blob/devel/ereuse_devicehub/tests/fixtures/snapshot/71a4%20eee-pc%20erasure%20real.json) with the size of the hard-drive, and I remember cases with the speed of the CPU (being thousands of Ghz) . [See here](https://devicehub.ereuse.org/api.html#id1), at the bottom of the page (last paragraph), the schema with the unit sizes DeviceHub waits for.

In old versions of DDI (prior 7.0) they used LSHW to know the unit size, although sometimes this request returns `None`. DDI can use too some guessing: if a Hard drive has a size of >1000 is probably going to be in MB not in GB; the same for a clock speed of >10 for a Processor.

**Comment by ivilata** [comment]
@bustawin Hmmm, [here](https://devicehub.ereuse.org/api-endpoints.html#harddrive) I see (under "Response JSON Object") this:

> size (float) – Unit Code: mbyte (4L)

In the sample JSON file I see:

```json
        {
            "@type": "HardDrive", 
            […]
            "size": 152627.8359375, 
            […]
        }, 
```

That would be a 150 GB drive, which makes sense to me. Maybe MB are required actually?

**Comment by bustawin** [comment]
@ivilata totally right, I do not know what I saw :-)
