### ISSUE TITLE
Set a keyboard distribution

### ISSUE THREAD

**Issue by bustawin** [eReuse/device-inventory#52]
DDI has the default keyboard distribution set as Spanish, and it is a real pain to use with a non-Spanish keyboard. There should be an option, to easily set the distribution: for example, when initializing the server and, by using the config.ini, propagate it to the clients.

**Comment by ivilata** [comment]
A note for implementation: list the entries in ``/usr/share/X11/xkb/symbols`` (package ``xkb-data``, required by ``console-setup``), pick an entry as LAYOUT, then invoke ``loadkeys LAYOUT``.

**Comment by ivilata** [comment]
I'm developing a helper script in branch ``keyboard-layout-52``, but I noticed that it cannot work currently since the helper script runs before DDI and therefore the configuration file still hasn't been retrieved from the server. However, it would work with #55 in place.

**Comment by ivilata** [comment]
The current version in ``keyboard-layout-52`` asks for a keyboard layout before running DDI.  If the shared directory is mounted, it reads the ``KEYBOARD_LAYOUT`` option from the config files and, if it has a value, that layout is loaded and no questions are asked.

![virtualbox_test_23_12_2016_15_30_51](https://cloud.githubusercontent.com/assets/420791/21456050/542f2c4c-c925-11e6-8efa-d4f10b0f897e.png)
