### ISSUE TITLE
Show 'still alive' messages when stressing

### ISSUE THREAD

**Issue by bustawin** [eReuse/device-inventory#53]
When executing the stress test, there is no way to know if the machine hung in the process, because a faulty component; we only know if the machine shuts down (failure) or finishes the tests (success).

It should print a message (or another way) showing that the machine is still alive, responsive, and the test is being executed, maybe showing a timer with the remaining time.

**Comment by ivilata** [comment]
Adding this test to #40 since stress test integration is not yet complete.
