### ISSUE TITLE
Capture installation to server

### ISSUE THREAD

**Issue by ivilata** [eReuse/device-inventory#63]
As mentioned in #34, we may provide a script with DDI to ease capturing an existing installation and save it to the server, using ``fsarchiver savefs``. The workflow would be to boot some installation ISO (from the server or not), prepare the machine, then boot eReuseOS from a server and instead of registering the computer, capturing its installation to the server.

This depends weakly on #55 (for the script to be able to access configuration).

**Comment by bustawin** [comment]
I am trying fsarchiver with your guide and it is not so complicated, you need to have although some basic skills with the terminal; not so bad as this is optional stuff.
